{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "# 載入 .env 檔案\n",
    "load_dotenv()\n",
    "conn_string = os.getenv('RENDER_DATABASE')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "established\n"
     ]
    }
   ],
   "source": [
    "import psycopg2\n",
    "coon = psycopg2.connect(conn_string)\n",
    "print(\"established\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "conn_string = \"postgresql://tvdi_1ggs_user:ZlMwMdBfpmaLGpdOP6SeglBKPlmZfXVf@dpg-d0qh8abe5dus739il5p0-a.singapore-postgres.render.com/tvdi_1ggs\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "established\n"
     ]
    }
   ],
   "source": [
    "import psycopg2\n",
    "\n",
    "try:\n",
    "    conn = psycopg2.connect(conn_string)\n",
    "    print(\"established\")\n",
    "except psycopg2.OperationalError as e:\n",
    "    print(\"連線失敗\")\n",
    "    print(e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import psycopg2\n",
    "from dotenv import load_dotenv\n",
    "load_dotenv()\n",
    "conn_string = os.getenv('RENDER_DATABASE')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: psycopg2-binary in /opt/anaconda3/envs/flask/lib/python3.11/site-packages (2.9.10)\n"
     ]
    }
   ],
   "source": [
    "!pip install psycopg2-binary"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "ename": "OperationalError",
     "evalue": "connection to server on socket \"/tmp/.s.PGSQL.5432\" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mOperationalError\u001b[39m                          Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[11]\u001b[39m\u001b[32m, line 2\u001b[39m\n\u001b[32m      1\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mpsycopg2\u001b[39;00m\n\u001b[32m----> \u001b[39m\u001b[32m2\u001b[39m conn = \u001b[43mpsycopg2\u001b[49m\u001b[43m.\u001b[49m\u001b[43mconnect\u001b[49m\u001b[43m(\u001b[49m\u001b[43mconn_string\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m      4\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m      5\u001b[39m     \u001b[38;5;28;01mwith\u001b[39;00m psycopg2.connect(conn_string) \u001b[38;5;28;01mas\u001b[39;00m conn:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/opt/anaconda3/envs/flask/lib/python3.11/site-packages/psycopg2/__init__.py:122\u001b[39m, in \u001b[36mconnect\u001b[39m\u001b[34m(dsn, connection_factory, cursor_factory, **kwargs)\u001b[39m\n\u001b[32m    119\u001b[39m     kwasync[\u001b[33m'\u001b[39m\u001b[33masync_\u001b[39m\u001b[33m'\u001b[39m] = kwargs.pop(\u001b[33m'\u001b[39m\u001b[33masync_\u001b[39m\u001b[33m'\u001b[39m)\n\u001b[32m    121\u001b[39m dsn = _ext.make_dsn(dsn, **kwargs)\n\u001b[32m--> \u001b[39m\u001b[32m122\u001b[39m conn = \u001b[43m_connect\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdsn\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mconnection_factory\u001b[49m\u001b[43m=\u001b[49m\u001b[43mconnection_factory\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwasync\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    123\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m cursor_factory \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m    124\u001b[39m     conn.cursor_factory = cursor_factory\n",
      "\u001b[31mOperationalError\u001b[39m: connection to server on socket \"/tmp/.s.PGSQL.5432\" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n"
     ]
    }
   ],
   "source": [
    "import psycopg2\n",
    "conn = psycopg2.connect(conn_string)\n",
    "\n",
    "try:\n",
    "    with psycopg2.connect(conn_string) as conn:\n",
    "        print(\"連線成功\")\n",
    "except Exception as e:\n",
    "    print(\"連線或查詢發生錯誤：\",e)        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[(2, '委外/補助 招生訊息', datetime.date(2025, 5, 21), '本年度公務預算委外辦理失業者職能培育相關課程已陸續開放招生，歡迎報名！\\n※附件各班之開結訓日期為預訂，如未達規定之最低開班人數則將辦理延班或停班。\\n※報名時間、流程或相關課程資訊請電洽各承訓單位。'), (3, '114年就安委外《職能培育》課程一覽表', datetime.date(2025, 2, 21), '本年度就安基金委外辦理失業者職能培育相關課程已陸續開放招生，歡迎報名！本年度就安基金委外辦理失業者職能培育相關課程已陸續開放招生，歡迎報名！\\n※附件各班之開結訓日期為預訂，如未達規定之最低開班人數則將辦理延班或停班。\\n※報名時間、流程或相關課程資訊請電洽各承訓單位。\\n※凡設籍臺北市之市民或於臺北市有居住事實之新住民，參加職業訓練期間如有托兒托老之照護需求，可申請臺北市政府職業訓練照護補助，詳情請洽承訓單位。\\n※附件各班之開結訓日期為預訂，如未達規定之最低開班人數則將辦理延班或停班。\\n※報名時間、流程或相關課程資訊請電洽各承訓單位。\\n※凡設籍臺北市之市民或於臺北市有居住事實之新住民，參加職業訓練期間如有托兒托老之照護需求，可申請臺北市政府職業訓練照護補助，詳情請洽承訓單位。'), (4, '114年臺北市照顧服務員訓練(補助班)課程一覽表', datetime.date(2025, 1, 21), '注意事項：\\n各班報名時間與相關課程資訊請洽各承訓單位。\\n各班如招訓人數未達規定將辦理停班或延班。'), (5, '114年度臺北市照顧服務員訓練課程民間自辦班(自費班)一覽表', datetime.date(2025, 1, 20), '注意事項：\\n1.課程之開結訓日期為預訂，實際開課以經權管機關核備通過為主\\n2.各班報名時間與相關課程資訊請洽各承訓單位  '), (1, '114年公務預算委外《職能進修》課程一覽表', datetime.date(2025, 5, 24), '臺北市職能發展學院除自辦職能培育課程外，亦委託其他訓練機構辦理多元化職能訓練，提供更多樣化的選擇。114年度之公務預算委外職能進修課程相關訊息歡迎透過本學院網站查詢www.tvdi.gov.taipei，報名請逕洽以下各承訓單位聯絡電話及承辦人。')]\n"
     ]
    }
   ],
   "source": [
    "import psycopg2\n",
    "from psycopg2 import OperationalError\n",
    "try:\n",
    "    conn = psycopg2.connect(conn_string)\n",
    "    with conn.cursor() as cur:\n",
    "        sql = \"SELECT * FROM 最新消息2\"\n",
    "        cur.execute(sql)\n",
    "        # 取得所有資料\n",
    "        rows = cur.fetchall()\n",
    "        print(rows)\n",
    "except OperationalError as e:\n",
    "    print(\"連線失敗\")\n",
    "    print(e)\n",
    "\n",
    "    conn.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "flask",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
